image: python:3.11

stages:
  - lint
  - test

before_script:
  - apt-get update -y
  - apt-get install -y libgirepository1.0-dev libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
  - pip install pydbus
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -e .[test,lint]

critical_lint:
  stage: lint
  script:
    - .venv/bin/pylint --ignore tui.py,gnome.py -E src
  allow_failure: true

ruff:
  stage: lint
  script:
    - .venv/bin/ruff check .
  allow_failure: true

pylint:
  stage: lint
  script:
    - .venv/bin/pylint src
  allow_failure: true

test:
  stage: test
  script:
    - .venv/bin/pytest
