image: python:3.11

stages:
  - lint
  - test
  - release
  - deploy

pages:
  stage: deploy
  script:
    - pip install .[docs]
    - sphinx-build -b html docs/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

before_script:
  - apt-get update -y
  - apt-get install -y libgirepository1.0-dev libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
  - pip install uv
  - uv pip install --system .[dev,test,lint]

publish_release:
  stage: release
  image: python:3.11
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script: []
  script:
    - pip install python-semantic-release
    - git config --global user.name "semantic-release-bot"
    - git config --global user.email "semantic-release@rai-project.com"
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - semantic-release version
    - semantic-release publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
critical_lint:
  stage: lint
  script:
    - pylint --ignore tui.py,gnome.py -E src
  allow_failure: true

ruff:
  stage: lint
  script:
    - ruff check .
  allow_failure: true

pylint:
  stage: lint
  script:
    - pylint src
  allow_failure: true

test:
  stage: test
  script:
    - pytest
