[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rai"
version = "0.1.1"
description = "Rich AI - The Intelligent AI assistant and agent ecosystem for Linux"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}

dependencies = [
    "python-dotenv",
    "agno>=2.0",
    "rich",
    "click>=8.1,<8.3",
    "ollama",
    "packaging",
    "textual",
    "prompt_toolkit",
    "sqlalchemy",
    "python-gitlab",
    "fastapi",
    "uvicorn[standard]",
    "httpx",
    "returns",
]

[project.optional-dependencies]
anthropic = ["anthropic"]
gemini = ["google-generativeai"]
openai = ["openai"]
groq = ["groq"]
test = ["pytest", "pytest-asyncio", "pytest-cov", "pydantic-ai"]
lint = ["ruff", "pylint"]
dev = ["rai[test]", "rai[lint]", "rai[tools]"]
gnome-tools = ["pydbus", "pygobject"]
tts = ["piper-tts", "sounddevice", "requests"]
pydantic-ai = ["pydantic-ai"]
docs = ["sphinx", "myst-parser", "furo", "sphinx-autobuild"]
tools = [
    "duckduckgo-search",
    "wikipedia",
    "arxiv",
    "pypdf",
    "tavily-python",
    "yfinance",
]
all = [
    "rai[anthropic]",
    "rai[gemini]",
    "rai[openai]",
    "rai[groq]",
    "rai[gnome-tools]",
    "rai[tts]",
    "rai[pydantic-ai]",
    "rai[tools]",
]

[project.scripts]
rai = "rai.cli:cli"
# rai-tui = "rai.tui:run_tui_cli"

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"


[tool.ruff.lint]
select = ["PL", "ANN"]


[tool.pylint]
max-line-length=108

[tool.pylint.typing]

[tool.semantic_release]
version_variable = "src/rai/__init__.py:__version__"
version_toml = ["pyproject.toml:project.version"]
major_on_zero = false
branch = "main"
upload_to_repository = false
upload_to_release = true
build_command = "pip install build && python -m build"

[tool.semantic_release.changelog]
template_dir = "templates"
exclude_commit_patterns = []

[tool.semantic_release.branches.main]
match = "main"
