"""Versioned domain contracts for the RAI embodiment kernel."""

from .records import (
    ActionFailure,
    ActionResult,
    CapabilityRequest,
    Claim,
    ContextManifest,
    ContextManifestItem,
    ContextPackage,
    DataClass,
    DeviceDescriptor,
    Episode,
    InferenceBudget,
    MediaReference,
    Observation,
    PolicyDecision,
    PolicyOutcome,
    ProducerIdentity,
    ProvenanceReference,
    RiskClass,
    Task,
    UsageRecord,
    parse_record,
)

__all__ = [
    "ActionFailure",
    "ActionResult",
    "CapabilityRequest",
    "Claim",
    "ContextManifest",
    "ContextManifestItem",
    "ContextPackage",
    "DataClass",
    "DeviceDescriptor",
    "Episode",
    "InferenceBudget",
    "MediaReference",
    "Observation",
    "PolicyDecision",
    "PolicyOutcome",
    "ProducerIdentity",
    "ProvenanceReference",
    "RiskClass",
    "Task",
    "UsageRecord",
    "parse_record",
]
