"""Rich Assistant package for graph-memory conversation and reasoning."""

from .audit import (
    AssistantAuditEntry,
    AssistantAuditLedger,
    InMemoryAssistantAuditLedger,
    JsonlAssistantAuditLedger,
)
from .backends.deterministic import DeterministicAssistantBackend
from .backends.local import LocalAssistantBackend
from .context import AssistantContextBuilder
from .diagnostics import MemoryDiagnosticReport, MemoryStageDiagnostic, diagnose_memory
from .derived import VerifiedDerivedClaim, write_verified_derived_claim
from .extraction import (
    ExtractedClaimKind,
    ExtractedMemoryCandidate,
    MemoryExtractionOutput,
    SchemaConstrainedMemoryExtractor,
)
from .evidence import RichHistoryEvidenceProvider
from .evaluation import (
    BackendRetrievalAnswerEvaluator,
    RetrievalAnswerEvaluator,
    RetrievalAnswerEvaluation,
    RetrievalChannelAggregate,
    RetrievalChannelMeasurement,
    RetrievalChannel,
    RetrievalCorpusClaim,
    RetrievalCorpusRelation,
    RetrievalCorpusTurn,
    RetrievalEvaluationCase,
    RetrievalEvaluationCorpus,
    RetrievalEvaluationRun,
    aggregate_retrieval_run,
    evaluate_retrieval_floor,
    load_retrieval_evaluation_corpus,
    seed_retrieval_evaluation_corpus,
)
from .ports import (
    AssistantModelBackend,
    AssistantEvidence,
    AssistantEvidenceProvider,
    AssistantSessionSummary,
    MemoryGraphStore,
    MemoryProposalExtractor,
    MemoryQuery,
)
from .query import MemoryQueryResolver
from .routing_evaluation import (
    ContextRoutingEvaluationCase,
    ContextRoutingEvaluationRun,
    ContextRoutingAggregate,
    ContextRoutingMeasurement,
    aggregate_context_routing,
    evaluate_context_routing,
)
from .records import (
    AnyAssistantRecord,
    AssistantCandidate,
    AssistantContextManifest,
    AssistantContextManifestItem,
    AssistantContextPackage,
    AssistantResponse,
    AssistantSessionId,
    ConversationTurn,
    InferenceRequest,
    MemoryOperation,
    MemoryOperationKind,
    MemoryProposal,
    MemoryRecord,
    MemoryRelation,
    MemoryRelationKind,
    parse_assistant_record,
)
from .service import AssistantService
from .store import SQLiteMemoryGraphStore
from .summary import GroundedClaimSummaryProvider, validate_grounded_summary

__all__ = [
    "AnyAssistantRecord",
    "AssistantAuditEntry",
    "AssistantAuditLedger",
    "AssistantCandidate",
    "AssistantContextBuilder",
    "AssistantContextManifest",
    "AssistantContextManifestItem",
    "AssistantContextPackage",
    "AssistantEvidence",
    "AssistantEvidenceProvider",
    "AssistantModelBackend",
    "AssistantResponse",
    "AssistantService",
    "AssistantSessionSummary",
    "AssistantSessionId",
    "BackendRetrievalAnswerEvaluator",
    "ConversationTurn",
    "ContextRoutingEvaluationCase",
    "ContextRoutingEvaluationRun",
    "ContextRoutingAggregate",
    "ContextRoutingMeasurement",
    "DeterministicAssistantBackend",
    "InMemoryAssistantAuditLedger",
    "InferenceRequest",
    "JsonlAssistantAuditLedger",
    "LocalAssistantBackend",
    "MemoryGraphStore",
    "MemoryProposalExtractor",
    "MemoryExtractionOutput",
    "ExtractedClaimKind",
    "ExtractedMemoryCandidate",
    "MemoryDiagnosticReport",
    "MemoryOperation",
    "MemoryOperationKind",
    "MemoryProposal",
    "MemoryQuery",
    "MemoryQueryResolver",
    "MemoryRecord",
    "MemoryRelation",
    "MemoryRelationKind",
    "MemoryStageDiagnostic",
    "RichHistoryEvidenceProvider",
    "GroundedClaimSummaryProvider",
    "RetrievalAnswerEvaluator",
    "RetrievalAnswerEvaluation",
    "RetrievalChannel",
    "RetrievalChannelAggregate",
    "RetrievalChannelMeasurement",
    "RetrievalCorpusClaim",
    "RetrievalCorpusRelation",
    "RetrievalCorpusTurn",
    "RetrievalEvaluationCase",
    "RetrievalEvaluationCorpus",
    "RetrievalEvaluationRun",
    "SQLiteMemoryGraphStore",
    "SchemaConstrainedMemoryExtractor",
    "parse_assistant_record",
    "diagnose_memory",
    "evaluate_retrieval_floor",
    "evaluate_context_routing",
    "load_retrieval_evaluation_corpus",
    "seed_retrieval_evaluation_corpus",
    "validate_grounded_summary",
    "VerifiedDerivedClaim",
    "write_verified_derived_claim",
    "aggregate_retrieval_run",
    "aggregate_context_routing",
]
